export const GET_TEXT_ANALYSIS_PENDING = 'GET_TEXT_ANALYSIS_PENDING';
export const GET_TEXT_ANALYSIS_SUCCESS = 'GET_TEXT_ANALYSIS_SUCCESS';
export const GET_TEXT_ANALYSIS_FAILURE = 'GET_TEXT_ANALYSIS_FAILURE';