export const POST_ENTRY_SHEET_PENDING = 'POST_ENTRY_SHEET_PENDING';
export const POST_ENTRY_SHEET_SUCCESS = 'POST_ENTRY_SHEET_SUCCESS';
export const POST_ENTRY_SHEET_FAILURE = 'POST_ENTRY_SHEET_FAILURE';